### PR TITLE
Update arch testing

### PR DESCRIPTION
**Pull request by petems**
Hi @jantman!

I've been using this repo to setup Arch on my old Macbook, been awesome so far, thank you!

Here's a PR to update the beaker setup to work with the upstream, plus an issue that I caught in the testing 👍

### CODE REVIEW

**Comment by jantman** [comment]
Oh wow, thanks! I guess it's pretty obvious that I wrote the bulk of this code quite a while ago, and haven't quite kept up with it... especially since I believe I could actually have it all running in Travis these days, using a Dockerized SUT (the problem there might be finding an up-to-date Arch Docker image, which I may need for another project anyway).

But it's really cool to see someone else making use of this. I should take better care of the code... while I run this weekly or so, the code only gets major exercise when I get a new machine or completely wipe one, and it's been well over a year now.

Let me pull this down and test it locally...

**Comment by jantman** [comment]
Ok, I'm having some issues with the Beaker specs locally. I'll try and dig into the problem... I *think* it *may* be rvm-related...

**Comment by jantman** [comment]
Ok, it appears that the Vagrant/rvm related issues I was having were because:

1. My vagrant install was broken. Fixed that.
2. The Gemfile still had ``vagrant-wrapper`` in it, which caused all sorts of awful problems.

After removing vagrant-wrapper from the Gemfile, I got beaker to at least run the tests.

However, I'm seeing spec failures on all of the ``archlinux_macbookretina::touchpad`` specs... I'm going to fix up the above (Gemfile) and those specs in master, after merging this.

Thanks __so__ much for this!

**Comment by petems** [comment]
Oh yeah, Vagrant-wrapper is a real pain. I have a complicated vagrant setup because I'm developing a vagrant plugin right now so it messes up the Ruby path, so the only way I can get it working is with the wrapper...

**Comment by jantman** [comment]
I had that for a while... https://github.com/jantman/vagrant-r10k

I remember all sorts of woes with vagrant-wrapper and Beaker a while ago...

**Pull request merged**
